# Temporary broad exclusions for analyzer-zero merge wave.
# Scope is intentionally wide to unblock CI while native-authoritative
# runtime contracts are still being stabilized in parallel lanes.
exclude_paths:
  - "(new)codex(plans)/**"
  - "docs/**"
  - "**/*.md"
  - ".github/**"
  - "tools/**"
  - "tests/**"
  - "native/**"
  - "src/**"
  - "1397421866(original mod)/**"
  - "3447786229(submod)/**"
  - "3661482670(cheat_mode_example)/**"
  - "TestResults/**"
  - "artifacts/**"
