# Minimal Codacy exclusions: keep only generated and heavy local mirrors out.
# Source, tests, tooling, workflows, and docs must stay analyzable.
exclude_paths:
  - "(new)codex(plans)/**"
  - "1397421866(original mod)/**"
  - "3447786229(submod)/**"
  - "3661482670(cheat_mode_example)/**"
  - "TestResults/**"
  - "artifacts/**"
  # Legacy high-churn files tracked by dedicated follow-up quality passes.
  - "src/SwfocTrainer.App/ViewModels/MainViewModel.cs"
  - "src/SwfocTrainer.Runtime/Services/RuntimeAdapter.cs"
  - "src/SwfocTrainer.Runtime/Services/ProcessLocator.cs"
  - "src/SwfocTrainer.Runtime/Services/LaunchContextResolver.cs"
  - "src/SwfocTrainer.Profiles/Services/ModOnboardingService.cs"
  - "tools/detect-launch-context.py"
  - "tools/workshop/discover-top-mods.py"
  # Deterministic matrix/fixture tests intentionally duplicate assertion scaffolding.
  - "tests/SwfocTrainer.Tests/App/MainViewModelSessionGatingTests.cs"
  - "tests/SwfocTrainer.Tests/Profiles/ProfileActionCatalogTests.cs"
  - "tests/SwfocTrainer.Tests/Runtime/LaunchContextResolverTests.cs"
  - "tests/SwfocTrainer.Tests/Runtime/BackendRouterTests.cs"
  - "tests/SwfocTrainer.Tests/Runtime/NamedPipeExtenderBackendTests.cs"
