# Minimal Codacy exclusions: keep only generated and heavy local mirrors out.
# Source, tests, tooling, workflows, and docs must stay analyzable.
exclude_paths:
  - "(new)codex(plans)/**"
  - "1397421866(original mod)/**"
  - "3447786229(submod)/**"
  - "3661482670(cheat_mode_example)/**"
  - "TestResults/**"
  - "artifacts/**"
