namespace SwfocTrainer.Core.Models;

/// <summary>
/// Stable reason-code taxonomy used by attach, capability routing, runtime execution,
/// helper fallback, safety gating, and rollback diagnostics.
/// </summary>
public enum RuntimeReasonCode
{
    UNKNOWN = 0,

    // ATTACH_*
    ATTACH_HOST_SELECTED,
    ATTACH_NO_PROCESS,
    ATTACH_TARGET_MISMATCH,
    ATTACH_HOST_AMBIGUOUS,
    ATTACH_PROFILE_MISMATCH,

    // CAPABILITY_*
    CAPABILITY_PROBE_PASS,
    CAPABILITY_UNKNOWN,
    CAPABILITY_REQUIRED_MISSING,
    CAPABILITY_BACKEND_UNAVAILABLE,
    CAPABILITY_FEATURE_EXPERIMENTAL,
    CAPABILITY_ANCHOR_INVALID,
    CAPABILITY_ANCHOR_UNREADABLE,

    // MODE_*
    MODE_GUARD_BLOCKED,
    MODE_UNKNOWN,
    MODE_STRICT_TACTICAL_UNSPECIFIED,

    // HOOK_*
    HOOK_INSTALL_FAILED,
    HOOK_UNINSTALL_FAILED,
    HOOK_BYTES_MISMATCH,
    HOOK_CONFLICT,

    // PATCH_*
    PATTERN_MISSING,
    PATTERN_NOT_UNIQUE,
    FALLBACK_DISABLED,
    FALLBACK_APPLIED,
    FALLBACK_RESTORED,
    PATCH_RESTORE_STATE_MISSING,
    PATCH_RESTORE_APPLIED,

    // HELPER_*
    HELPER_NOT_DEPLOYED,
    HELPER_NOT_VERIFIED,
    HELPER_ROUTE_SELECTED,
    HELPER_BRIDGE_UNAVAILABLE,
    HELPER_ENTRYPOINT_NOT_FOUND,
    HELPER_INVOCATION_TIMEOUT,
    HELPER_INVOCATION_FAILED,
    HELPER_VERIFICATION_FAILED,
    HELPER_EXECUTION_APPLIED,

    // SAFETY_*
    SAFETY_FAIL_CLOSED,
    SAFETY_MUTATION_BLOCKED,

    // ROLLBACK_*
    ROLLBACK_SUCCESS,
    ROLLBACK_FAILED
}
