name: Feature Request
description: Propose a new capability or enhancement
title: "[Feature] "
labels:
  - type:feature
body:
  - type: input
    id: objective
    attributes:
      label: Objective
      placeholder: What user outcome should this enable?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Include concrete validation criteria.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - runtime
        - app
        - profiles
        - saves
        - tooling
        - ci
        - docs
    validations:
      required: true
