name: Feature Request
description: Propose a new capability or enhancement
title: "[Feature] "
labels:
  - type:feature
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      placeholder: What user outcome should this enable?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Include concrete validation criteria.
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk level
      options:
        - low
        - medium
        - high
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - runtime
        - app
        - profiles
        - saves
        - tooling
        - ci
        - docs
    validations:
      required: true

  - type: textarea
    id: evidence_commands
    attributes:
      label: Evidence command list
      value: |
        dotnet test tests/SwfocTrainer.Tests/SwfocTrainer.Tests.csproj -c Release --no-build --filter "FullyQualifiedName!~SwfocTrainer.Tests.Profiles.Live&FullyQualifiedName!~RuntimeAttachSmokeTests"
    validations:
      required: true
